# Generated by Django 5.1.7 on 2025-11-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
