# Generated by Django 5.1.7 on 2025-11-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_comment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='amount',
        ),
    ]
